#pragma once
#define MANYPACKER_VERSION "1.0.1"
#define MANYPACKER_NAME "ManyPacker"

#define MANYPACKER_FULL_NAME MANYPACKER_NAME " " MANYPACKER_VERSION
#define MANYPACKER_REG L"Software\\" MANYPACKER_NAME