# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: ./ManyPacker.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
          platform: [x64, x86]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
          name: ${{matrix.configuration}} binaries ${{matrix.platform}}
          path: |
            D:\a\ManyPacker\ManyPacker\${{matrix.platform}}\${{matrix.configuration}}\ManyPacker.exe
